"""Baseline model namespace."""

from .core import (
    BASELINE_NAMES,
    CD_REL,
    ComparisonConfig,
    DegreePopularityBaseline,
    GenericHGATBaseline,
    HGATNoEdgeAttrBaseline,
    HeteroSAGEBaseline,
    LEGACY_BASELINE_ALIASES,
    LightGCNCDBaseline,
    MatrixFactorizationBaseline,
    PairMLPBaseline,
    RGCNCDBaseline,
    build_baseline,
    compare_main_and_baselines,
    evaluate_baseline,
    load_main_model_from_checkpoint,
    normalize_baseline_name,
    train_baseline,
)

__all__ = [
    "CD_REL",
    "BASELINE_NAMES",
    "ComparisonConfig",
    "DegreePopularityBaseline",
    "MatrixFactorizationBaseline",
    "PairMLPBaseline",
    "LightGCNCDBaseline",
    "RGCNCDBaseline",
    "HeteroSAGEBaseline",
    "HGATNoEdgeAttrBaseline",
    "GenericHGATBaseline",
    "LEGACY_BASELINE_ALIASES",
    "normalize_baseline_name",
    "build_baseline",
    "train_baseline",
    "evaluate_baseline",
    "load_main_model_from_checkpoint",
    "compare_main_and_baselines",
]
